# **Machine Learning without Pipeline - 2**

## **Import Required Libraries**

In [1]:
import pickle
import numpy as np
import warnings
warnings.filterwarnings("ignore")

## **Load the Model and Encoders**

In [2]:
# Load the model and the encoders
ohe_sex = pickle.load(open("D:\Coding\Models\ohe_sex.pkl", "rb"))
ohe_embarked = pickle.load(open("D:\Coding\Models\ohe_embarked.pkl", "rb"))
clf = pickle.load(open("D:\Coding\Models\decision_tree_model.pkl", "rb"))

## **Take User Input**

In [3]:
# Assume user input
# Pclass / Sex / Age / SibSp / Parch / Fare / Embarked
test_input = np.array([2, "male", 22.0, 1, 0, 25.0, "S"], dtype=object).reshape(1, 7)

In [4]:
test_input

array([[2, 'male', 22.0, 1, 0, 25.0, 'S']], dtype=object)

## **Transform the Input using Encoders**

In [5]:
 # Encode the 'Sex'
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))
test_input_sex

array([[0., 1.]])

In [6]:
# Encode the 'Embarked'
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1, 1))
test_input_embarked

array([[0., 0., 1.]])

In [7]:
# Extract the 'Age'
test_input_age = test_input[:, 2].reshape(1, 1)
test_input_age

array([[22.0]], dtype=object)

In [8]:
# Extract the remaining columns from test_input data
test_input_rem = test_input[:, [0, 3, 4, 5]]
test_input_rem

array([[2, 1, 0, 25.0]], dtype=object)

In [9]:
# Merge the encoded data with the test input data
test_input_merged = np.concatenate((test_input_rem, test_input_age, test_input_sex, test_input_embarked), axis=1)
test_input_merged

array([[2, 1, 0, 25.0, 22.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [10]:
test_input_merged.shape

(1, 10)

## **Predict the Input Data with the Model**

In [11]:
predict = clf.predict(test_input_merged)
predict

array([0], dtype=int64)