# Multiple Linear Regression

## 01. Import the Essential Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

## 02. Creating a DataFrame

In [2]:
df = pd.read_csv("Housing.csv")
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement   
0  13300000  7420         4          2        3      yes        no       no  \
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [11]:
# Slecting only the fields which have numerical values
new_df = df[["price", "area", "bedrooms", "bathrooms"]]
new_df.head()

price  area  bedrooms  bathrooms
0  13300000  7420         4          2
1  12250000  8960         4          4
2  12250000  9960         3          2
3  12215000  7500         4          2
4  11410000  7420         4          1

## 03. Creating Linear Regression Object

In [13]:
# Defining independent(x) and dependent(y) variables
# In this case, independent variable(x) will be 'area', 'bedrooms', 'bathrooms', 'stories', 'parking'
# and dependent variable will be 'price'
x = new_df[["area", "bedrooms", "bathrooms"]]
y = new_df[["price"]]

In [14]:
# Creating a Linear Regression model
reg = linear_model.LinearRegression()
# Training the model using the x and y
reg.fit(x, y)

LinearRegression()

## 04. Getting the Coefficients
Linear Equation:<br>
**y = m1x1 + m2x2 + m3x3 + ... + mnxn + c**<br>
where,
y = dependent variable<br>
m = slope<br>
x = independent variables<br>
c = y-intercept<br>

In [15]:
# Getting the slopes for all the independent variables
reg.coef_

array([[3.78762754e+02, 4.06820034e+05, 1.38604950e+06]])

In [16]:
# Getting the y-intercept
reg.intercept_

array([-173171.60763263])

## 05. Predicting Price of Houses

In [22]:
reg.predict([[0, 4, 3]])

C:\Users\KRISH\miniconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[43488532.37932754]])