In [1]:
import numpy as np

In [2]:
myArr1D = np.array([1, 2, 3, 4])
myArr1D

array([1, 2, 3, 4])

In [3]:
myArr2D = np.array([[1, 2, 3], [4, 5, 6]])
myArr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
myArr1D.ndim

1

In [5]:
myArr2D.ndim

2

In [7]:
myArr1D.itemsize

4

In [8]:
myArr1D.dtype

dtype('int32')

In [9]:
myArr2D = np.array([[1, 2, 3], [4, 5, 6]], dtype="float64")
myArr2D

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
myArr2D.itemsize

8

In [11]:
myArr2D.size

6

In [12]:
myArr2D.shape

(2, 3)

In [13]:
complex_array = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
complex_array

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [14]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
np.reshape(myArr2D, (3, 2))

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [26]:
myArr2D.ravel()

array([1., 2., 3., 4., 5., 6.])

In [27]:
myArr2D.min()

1.0

In [28]:
myArr2D.max()

6.0

In [29]:
myArr2D.sum()

21.0

In [31]:
myArr2D

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
myArr2D.sum(axis=0)

array([5., 7., 9.])

In [32]:
myArr2D.sum(axis=1)

array([ 6., 15.])

In [33]:
np.sqrt(myArr1D)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [34]:
np.std(myArr2D)

1.707825127659933

In [36]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [37]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [38]:
a + b

array([[ 6,  8],
       [10, 12]])

In [39]:
a - b

array([[-4, -4],
       [-4, -4]])

In [40]:
a * b

array([[ 5, 12],
       [21, 32]])

In [41]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [42]:
a.dot(b)

array([[19, 22],
       [43, 50]])