In [2]:
import numpy as np

In [3]:
myArr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
myArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
myArr.sum(axis=0)

array([12, 15, 18])

In [5]:
myArr.max(axis=0)

array([7, 8, 9])

In [6]:
myArr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
myArr.flat

In [8]:
print(myArr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
