# **PyTorch Fundamentals**
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="20%">

PyTorch is an open-source machine learning library primarily developed by Facebook's AI Research lab (FAIR). It is widely used for deep learning applications and provides a flexible and efficient platform for building and training neural networks. PyTorch is known for its dynamic computation graph, which allows developers to change the architecture of their models on the fly, making it highly intuitive and user-friendly for research and development.

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/01_a_pytorch_workflow.png">

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.3.1+cu121


In [30]:
# Check the GPU available
# !nvidia-smi

## **Introduction to Tensors**
A PyTorch Tensor is a multi-dimensional array or matrix that holds elements of a single data type. It is similar to a NumPy array but with additional capabilities that make it more suitable for deep learning and high-performance computing.

Here are some key features of a PyTorch Tensor:

1. **Data Storage**: Tensors can store data in various dimensions (1D, 2D, 3D, etc.). For example, a 1D tensor is like a vector, a 2D tensor is like a matrix, and higher-dimensional tensors can represent more complex data structures.

2. **GPU Acceleration**: Unlike NumPy arrays, PyTorch Tensors can be moved to GPU memory, allowing for faster computation, especially in deep learning tasks.

3. **Automatic Differentiation**: PyTorch provides a feature called Autograd that allows for automatic computation of gradients. This is particularly useful for training neural networks, where backpropagation requires the calculation of gradients.

4. **Data Types**: PyTorch Tensors support various data types such as `float32`, `float64`, `int32`, `int64`, etc. The data type can be specified when creating a tensor.

5. **Operations**: PyTorch provides a wide range of operations that can be performed on Tensors, such as mathematical operations, linear algebra, and random sampling.

<img src="https://miro.medium.com/v2/resize:fit:880/1*WbLIc4-xIOfHiO2oWzimyA.png" width="100%">

### **Creating Tensors**

#### **Scalar**
A scalar is a single number or a single value that represents a quantity. In mathematics and computer science, it is a simple, one-dimensional value without any additional structure, like direction or components.

**Examples of Scalars:**
- A single integer: `5`
- A floating-point number: `3.14`
- A real number: `-2.7`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python list
scalar.item()

7

#### **Vector**
A vector is a mathematical object that has both magnitude (size) and direction. Vectors are used to represent quantities that involve both of these properties, such as velocity, force, and displacement. In PyTorch, a vector can be represented as a 1-dimensional tensor or array.

**Key Characteristics of Vectors:**
- **Magnitude**: The length or size of the vector.
- **Direction**: The direction in which the vector is pointing.


In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

#### **Matrix**
A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. Matrices are fundamental objects in mathematics and are widely used in various fields such as linear algebra, computer graphics, machine learning, and physics.

**Structure of a Matrix:**
- **Rows and Columns**: A matrix is organized into rows (horizontal lines) and columns (vertical lines).
- **Elements**: Each element in a matrix is identified by its position within the matrix, typically denoted as $a_{ij}$, where $i$ is the row index and $j$ is the column index.

**Example of a 2x3 Matrix:**
$$
\mathbf{A} =
\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}
$$
This is a matrix with 2 rows and 3 columns.


In [ ]:
# MATRIX
MATRIX = torch.tensor([[3, 4],
                       [6, 7]])
MATRIX

tensor([[3, 4],
        [6, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

#### **Tensor**
A tensor is a generalization of scalars, vectors, and matrices to higher dimensions. Tensors are multi-dimensional arrays that can store data in more than two dimensions, making them a fundamental concept in various fields like physics, machine learning, and deep learning. In PyTorch, tensors are implemented as multi-dimensional arrays. PyTorch tensors are similar to NumPy arrays but come with additional features like GPU support and automatic differentiation.

**Key Characteristics of Tensors:**
- **Dimensions (or Rank)**: The number of indices required to specify an element in the tensor. This is also known as the tensor's rank or order.
  - **Scalar**: A 0-dimensional tensor (a single number).
  - **Vector**: A 1-dimensional tensor (a list of numbers).
  - **Matrix**: A 2-dimensional tensor (a grid of numbers).
  - **Higher-Dimensional Tensor**: A tensor with three or more dimensions.



In [13]:
# TENSOR
TENSOR = torch.tensor([[[2, 3, 4],
                        [5, 6, 7]],

                       [[8, 9, 6],
                        [1, 2, 3]]])
TENSOR

tensor([[[2, 3, 4],
         [5, 6, 7]],

        [[8, 9, 6],
         [1, 2, 3]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([2, 2, 3])

#### **Random Tensors**
A random tensor in PyTorch is a tensor whose elements are generated randomly according to a specified probability distribution. PyTorch provides several functions to create tensors filled with random values, each drawn from different distributions like uniform, normal (Gaussian), and others.

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random numbers`

In [19]:
# Create a random tensor of size (2, 3, 4)
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.0674, 0.4825, 0.7662, 0.3596],
         [0.3354, 0.5638, 0.6393, 0.9391],
         [0.5139, 0.9483, 0.2729, 0.2962]],

        [[0.3913, 0.3919, 0.5205, 0.9090],
         [0.5712, 0.2228, 0.1777, 0.9288],
         [0.5810, 0.9065, 0.1928, 0.1291]]])

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([2, 3, 4])

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channel, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### **Zeros and Ones**
In PyTorch, `zeros` and `ones` are functions used to create tensors filled entirely with zeros or ones, respectively. These functions are often used to initialize tensors in various machine learning tasks, such as setting up initial weights, biases, or input data.

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### **Creating a range of tensors and tensors-like**
In PyTorch, you can create a range of tensors using functions like `torch.arange` and `torch.linspace`, and you can create tensors with the same shape and properties as another tensor using functions like `torch.zeros_like`, `torch.ones_like`, and `torch.full_like`.

In [27]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1) # default step is 1
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### **Tensor Datatypes**
In PyTorch, tensors can have different data types (also known as `dtype`), which determine the type of data (e.g., integers, floating-point numbers) that the tensor can hold. The data type of a tensor is crucial for performance and accuracy, especially in computations involving large datasets or deep learning models.

**Common Tensor Data Types in PyTorch:**

1. **Floating-Point Types**:
   - **`torch.float32`** (`torch.float`): 32-bit floating-point (single precision). This is the most commonly used type for training neural networks.
   - **`torch.float64`** (`torch.double`): 64-bit floating-point (double precision). Used when more precision is needed.
   - **`torch.float16`** (`torch.half`): 16-bit floating-point (half precision). Often used in deep learning for reducing memory usage and speeding up computations, particularly on GPUs.

2. **Integer Types**:
   - **`torch.int8`**: 8-bit signed integer.
   - **`torch.uint8`**: 8-bit unsigned integer.
   - **`torch.int16`** (`torch.short`): 16-bit signed integer.
   - **`torch.int32`** (`torch.int`): 32-bit signed integer. Commonly used for general-purpose integer data.
   - **`torch.int64`** (`torch.long`): 64-bit signed integer. Often used for indexing and large-range integers.

3. **Boolean Type**:
   - **`torch.bool`**: Boolean type, where each element is either `True` or `False`.

4. **Complex Types**:
   - **`torch.complex64`**: 64-bit complex number, with 32 bits for the real part and 32 bits for the imaginary part.
   - **`torch.complex128`**: 128-bit complex number, with 64 bits for the real part and 64 bits for the imaginary part.

5. **Quantized Types** (used in model quantization):
   - **`torch.qint8`**: 8-bit signed integer used in quantized models.
   - **`torch.quint8`**: 8-bit unsigned integer used in quantized models.
   - **`torch.qint32`**: 32-bit signed integer used in quantized models.


🤔**Note:**<br>
Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
   1. Tensors not right datatype
   2. Tensors not right shape
   3. Tensors not on the right device

In [31]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g., float32 or float64)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)